### ISSUE TITLE
UnauthorizedError: jwt issuer invalid. expected: https://user.auth0.com

### ISSUE THREAD

**Issue by JayathmaChathurangani** [auth0-blog/reactjs-authentication-tutorial#6]
I followed all the steps found in the [blog](https://auth0.com/blog/reactjs-authentication-tutorial/). But when I am trying to access the "Celebrity Jokes" section which required authorised access the following error appear in the browser.

**GET http://localhost:3333/api/jokes/celebrity 401 (Unauthorized)
createError.js:16 Uncaught (in promise) Error: Request failed with status code 401
    at createError (createError.js:16)
    at settle (settle.js:18)
    at XMLHttpRequest.handleLoad (xhr.js:77)**

The error appear in the console of server side is this.

**UnauthorizedError: jwt issuer invalid. expected: https://user.auth0.com
    at E:\back-end\server\node_modules\express-jwt\lib\index.js:100:22
    at E:\back-end\server\node_modules\jsonwebtoken\index.js:155:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)**

 (Actually I replaced the **localhost** with my ip address as well). In {YOUR-AUTH0-DOMAIN} I put my value where I replaced **user** with correct value and here I just put a example value (https://**user**.auth0.com)

How to get rid of this?

**Comment by JayathmaChathurangani** [comment]
The error was with the format in which the issuer was entered. It should have additional forward slash at the end. Therefore the format is
https://user.auth0.com/

It would be great if sample values are given in the documentation for clear understanding.

**Comment by JayathmaChathurangani** [comment]
The error was with the format in which the issuer was entered. It should have additional forward slash at the end. Therefore the format is
https://user.auth0.com/

It would be great if sample values are given in the documentation for clear understanding.
